### ISSUE TITLE
NameError: global name 'device_id' is not defined

### ISSUE THREAD

**Issue by JarvisTheJelly** [Pixdigit/Project-Interstellar#1]
Traceback (most recent call last):
  File "Run.py", line 26, in <module>
    from src import main
  File "/home/jarvis/Documents/Workspace/Project-Interstellar/src/__init__.py", line 11, in <module>
    from main import main
  File "/home/jarvis/Documents/Workspace/Project-Interstellar/src/main.py", line 23, in <module>
    interface.init()
  File "/home/jarvis/Documents/Workspace/Project-Interstellar/src/interface.py", line 15, in init
    midi_in.init()
  File "/home/jarvis/Documents/Workspace/Project-Interstellar/src/midi_in.py", line 16, in init
    device = pygame.midi.Input(device_id)
NameError: global name 'device_id' is not defined

I'll see if I can fix it, but this was the first thing I got when I pulled the most recent code from GitHub.

**Comment by Pixdigit** [comment]
It has to do with pygame.midi. The program searches for devices but has not found one so there obviously is no device and no device_id.
