### ISSUE TITLE
Screen Width and Height Error.

### ISSUE THREAD

**Issue by sralse** [Pixdigit/Project-Interstellar#13]
Hi there, I've tried to get your program running, but I didn't get to fix screenx and the screeny values. I'm using two diffrent screens and the program messes up in a weird way, once I got the Screen width and height as non-user dependent variables, I bumped into an second and third error. The first one was Python self not able to properly detect my keyboard since have multiple keyboards connected. Then once I bypassed that, I bump into this: 
```
    from src import main
  File "/home/sralse/Downloads/Project-Interstellar-master/src/__init__.py", line 12, in <module>
    from main import main
  File "/home/sralse/Downloads/Project-Interstellar-master/src/main.py", line 31, in <module>
    menu.main()
  File "/home/sralse/Downloads/Project-Interstellar-master/src/menu.py", line 168, in main
    planet = create_planet(1200, 800)
  File "/home/sralse/Downloads/Project-Interstellar-master/src/menu.py", line 155, in __init__
    planet = pyganim.PygAnimation(planets)
  File "/home/sralse/Downloads/Project-Interstellar-master/libs/pyganim/pyganim/__init__.py", line 169, in __init__
    assert frame[1] > 0, 'Frame %s duration must be greater than zero.' % (i)
AssertionError: Frame 0 duration must be greater than zero.
```
I think this is because I messed with screenres, anyways, I can't really give you more feedback than this. I'm a beginner at python myself so.. Yeah I hope I can help ya out with some things Leave me a mail @ larscarre@gmail.com.

**Comment by Pixdigit** [comment]
Hmm wired. Woking on that part of the code and implementing a different technique to load the planet animation so it might get fixed in the next commit to main branch. Please test that out(I will push it in a few minutes).

**Comment by sralse** [comment]
Okay, I'd be glad to try!

**Comment by sralse** [comment]
Okay I bypassed it again, stil getting this error:
```
Traceback (most recent call last):
  File "Run.py", line 32, in <module>
    from src import main
  File "/home/sralse/Downloads/Project-Interstellar-master/Project-Interstellar-master/src/__init__.py", line 12, in <module>
    from main import main
  File "/home/sralse/Downloads/Project-Interstellar-master/Project-Interstellar-master/src/main.py", line 22, in <module>
    settings.init()
  File "/home/sralse/Downloads/Project-Interstellar-master/Project-Interstellar-master/src/settings.py", line 196, in init
    (screenx_current * ratio, screeny_current))
TypeError: integer argument expected, got float
```
Even when making the argument an integer it says it's a tuple... :/

**Comment by Pixdigit** [comment]
@sralse have you tried turning the line into ```(int(screenx_current * ratio), screeny_current)```

**Comment by sralse** [comment]
@Pixdigit Yep, tried that too. I made a Failsafe Graphic mode for your code. I'll commit in a second.

**Comment by sralse** [comment]
Fixed it: I added a debug text for the graphics. And failsafe mode. Your initial error was in the src/draw.py file; line 32; You subtracted the two things but you need to reverse it... you did Ysmall- Ybig, instead of Ybig - Ysmall, which resulted in an negative resolution. I committed.
