### ISSUE TITLE
On starting dev, crash

### ISSUE THREAD

**Issue by JarvisTheJelly** [Pixdigit/Project-Interstellar#9]
Project-Interstellar$ ./Run.sh
Loading time:3.789
Your seed is:6083860316226038
('Unexpected error:', <type 'exceptions.NameError'>)

Traceback (most recent call last):
  File "Run.py", line 27, in <module>
    from src import main
  File "/home/jarvis/Documents/other-people/ProjectInterstellar/ver0.0.3/Project-Interstellar/src/__init__.py", line 12, in <module>
    from main import main
  File "/home/jarvis/Documents/other-people/ProjectInterstellar/ver0.0.3/Project-Interstellar/src/main.py", line 72, in <module>
    main()
  File "/home/jarvis/Documents/other-people/ProjectInterstellar/ver0.0.3/Project-Interstellar/src/main.py", line 64, in main
    draw.ingame()
  File "/home/jarvis/Documents/other-people/ProjectInterstellar/ver0.0.3/Project-Interstellar/src/draw.py", line 45, in ingame
    status()
  File "/home/jarvis/Documents/other-people/ProjectInterstellar/ver0.0.3/Project-Interstellar/src/draw.py", line 194, in status
    settings.screeny_current - correcture_pos.h)
NameError: global name 'correcture_pos' is not defined

No clue, didn't have a problem in the main branch.

**Comment by Pixdigit** [comment]
The variable correcture_pos in src/draw.py is a global variable so I have no idea where this problem is coming from.

**Comment by Pixdigit** [comment]
The problem was that is the aspect ratio was 16/9 no correcture_pos was defined.
